### ISSUE TITLE
update to newer lv2-dev

### ISSUE THREAD

**Issue by rusk911** [brummer10/MelMatchEQ.lv2#6]
The plugin is failing to compile on Ubuntu Studio 24.04. As well as GxMatchEQ.lv2. May be others, haven't tried. While Ratatoile is compiled just fine.

```
~/MelMatchEQ.lv2$ make
. . , clean up
generate resource files,
g++ -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -fstack-protector -funroll-loops -ffast-math -fomit-frame-pointer -fstrength-reduce -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -msse3 -mfpmath=sse -mfxsr plugin/gx_melmatcheq.cpp  -I. -shared -lm -lm -Wl,-z,noexecstack  -o gx_melmatcheq.so
In file included from plugin/gx_melmatcheq.cpp:80:
plugin/gx_melmatcheq.h:25:10: fatal error: lv2.h: No such file or directory
   25 | #include <lv2.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:113: gx_melmatcheq] Error 1
```

**Comment by brummer10** [comment]
Could it be that you've installed the lv2 packages from KxStudio? 
Please install the standard headers from your distribution.

**Comment by rusk911** [comment]
Yes, that solved the problem.  Thank you!

**Comment by brummer10** [comment]
So I could close this.
